# -*- coding: utf-8 -*-
"""class8-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XPsAjx_vv7wNGJ5AHNBaFRMLp7Haqbv_
"""

#1 CRIE UMA FUNÇÃO PARA SUBTRAIR DOIS NÚMEROS
def subtracao():
  x1 = float(input('Digite um Numero a Subtrair:'))
  y1 = float(input('Digite um Numero a Subtrair:'))

  print(f'Este é o resultado:{x1-y1}')
subtracao()

#2 CRIE UMA FUNÇÃO PARA SOMAR DOIS NÚMEROS
def subtracao2():
  x2 = float(input('Digite um Numero a Somar:'))
  y2 = float(input('Digite um Numero a Somar:'))

  print(f'Este é o resultado:{x2+y2}')
subtracao2()

#3 CRIE UMA FUNÇÃO PARA DIVIDIR DOIS NÚMEROS
def subtracao3():
  if y3 == 0:
    print('Zero não pode ser divido.')
  x3 = int(input('Digite um Numero a Dividir:'))
  y3 = int(input('Digite um Numero a Dividir:'))
  print(f'Este é o resultado:{x3/y3}')
subtracao3()

#4 CRIE UMA FUNÇÃO PARA MULTIPLICAR DOIS NÚMEROS
def subtracao4():
  x4 = float(input('Digite um Numero a Multiplicar:'))
  y4 = float(input('Digite um Numero a Multiplicar:'))

  print(f'Este é o resultado:{x4*y4}')
subtracao4()

#5 CRIE UMA CALCULADORA, ONDE O USUÁRIO POSSO ESCOLHER AS OPERAÇÕES
def calc():
  operacao = input('Digite uma Operação:')

  if operacao == '*':
    subtracao4()
  elif operacao == '+':
    subtracao2()
  elif operacao == '-':
    subtracao()
  elif operacao == '/':
    subtracao3()
calc()