# -*- coding: utf-8 -*-
"""class8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S2L7rYnkc2j3KaE8MQagmDVD1vzi_xn_
"""

# 1 -  Crie uma tupla chamada frutas com pelo menos 5 frutas diferentes. Em seguida, acesse e imprima o terceiro elemento da tupla.
frutas = ('laranja', 'uva', 'goiaba', 'jaca', 'jambu')

print(frutas)
print(" ")
# for n in frutas:
print(frutas[2])

# 2 - Crie uma tupla chamada numeros com alguns números inteiros. Em seguida, converta essa tupla em uma lista e imprima a lista resultante.
numbers = (1,2,3,3,4,5)
lizt = list(numbers)

print(lizt)
print(" ")
# for n in lizt:
#   print(n)

# 3 - Crie uma tupla chamada `meses` com os nomes dos meses do ano até Setembro. Use um loop `for` para imprimir cada mês em uma linha separada.
meses = ("Janeiro","Fevereiro","Março","Abril",'Maio','Junho','Julho','Agosto',"Setembro")

print(meses)
print(" ")
for n in meses:
  print(n)

# 4 - Crie uma lista chamada notas com algumas notas de alunos. Em seguida, converta essa lista em uma tupla e imprima a tupla resultante.
lizt2 = [5,5.5,6.7,9.5,10]
tupla = tuple(lizt2)

print(tupla)
print(" ")
for n in tupla:
  print(n)

# 5 - Crie uma lista chamada `ponto` que represente as coordenadas (x, y) de um ponto. Em seguida, desempacote os elementos da lista em duas variáveis separadas (x e y) e imprima os valores.
point = [3.141592653584626,4.33832479]
x,y = point

print(x)
print(y)